language: python
python:
    - "2.7"
    - "3.3"
    - "3.4"
    - "3.5"
sudo: required
install:
    - sudo apt-get install liblapack-dev libblas-dev gfortran
    - pip install -v .
    - pip install -r requirements.txt
script:
    py.test
